### PR TITLE
remove winston, because it is not used

### PR DESCRIPTION
**Pull request by iamstarkov**

### CODE REVIEW

**Comment by iamstarkov** [comment]
@monkpow, @villadora, @simono, @himdel can you help out?

it breaks our builds

**Comment by iamstarkov** [comment]
maybe @monkpow

**Comment by iamstarkov** [comment]
@monkpow, @villadora, @simono, @himdel ping.

perhaps, you can add me to collaborators, so i can merge it and make a release. what do you think?

**Comment by monkpow** [comment]
Can you give details about how it  reaks the build?  Just pasting in the npm response is fine.  Adding winston logging is on the short term roadmap,  so Id like to understand the issue better.  Thanks.

**Comment by iamstarkov** [comment]
we use winston-logger in our app. the app is PWA with server-side, so we need to bundle it with webpack, so its not good for us to have several versions of the same lib.

we bumped winston, it turns out that winston released breaking change in minor update (the one "express-http-proxy" "uses"). npm/yarn didnt recognize it (obviously) and installed latest winston. as far as its breaking change, we had to rollback "express-http-proxy" bump. during investigation it turned out that "express-http-proxy" doesnt use winston after all. so i submitted PR to remove unused "winston"

**Comment by iamstarkov** [comment]
i mean express-http-proxy dont use winston, why are you concerned about its removal?

**Comment by monkpow** [comment]
@iamstarkov thanks for this.

**Comment by iamstarkov** [comment]
@monkpow thank you

**Pull request merged**
