### PR TITLE
Preserve body encoding

### PR DESCRIPTION
**Pull request by theo01**
This is needed if you want to be able to send data using multipart/form-data. Otherwise data are altered since the proxy assume an utf-8 encoding.

### CODE REVIEW

**Comment by monkpow** [comment]
Thanks for the change and the test.

If I understand my history correctly, the UTF-8 was added to patch an issue where (for some servers, like github) a UTF-8 header was required so the response body would be readable.    

Independent of the quality of your change, I think this might be an unexpected and breaking change for folks relying on the current to UTF-8 header insertion.

Can you add this change as option that can be passed to the proxy call?  E.g., by default users will continue to UTF-8, but have the option to choose a different encoding?

Thanks

**Comment by theo01** [comment]
From my understanding this utf-8 encoding comes from #36. This issue solves a problem where the proxy was hanging when body was already processed by another middelware, but is had nothing to do with request headers and it does not appear to be any reason to add this utf-8 encoding to getRawBody().

I think adding this utf-8 encoding was a breaking change that should be corrected. But I can also add a new option to preserve the body encoding.

**Comment by monkpow** [comment]
I agree with your general analysis of history; however the commit forcing utf-8 is six months old, so I'd assume that current users expect this behavior.  

I think that the best outcome is that we have a new option (something like reqBodyEncoding that would default to utf-8 if users haven't made a specific choice, and allow author to preserve encoding, or specify the encoding).   

This  will allow use to serve your (and additional) use cases without breaking folks who may be relying on the current behavior.

**Comment by monkpow** [comment]
This is a very nice patch.   Thank you for the revision.

**Comment by theo01** [comment]
Thanks.

When I wrote the test I realized, it runs on node v0.11 which is pretty old, do you plan to update that?

**Comment by monkpow** [comment]
Yes, I hope to fairly soon.

**Pull request merged**
