### PR TITLE
Add preIntercept method.

### PR DESCRIPTION
**Pull request by paulmillr**
This can be used to change headers. `intercept` doesn't work because the headers have already been sent at this point.

### CODE REVIEW

**Comment by shreeve** [comment]
Why is this failing checks?

This is a very useful addition, please consider adding it.

**Comment by monkpow** [comment]
Hi @shreeve, 

There is a small details link on the ```checks``` interface that you can use to see why this pull is failing.    This patch is also currently without tests or docs, so it can't be merged without additional work, even if it were passing.

I agree that the feature seems useful, and have added it to the backlog.

**Comment by sunshineo** [comment]
+1

**Comment by paulmillr** [comment]
@monkpow done.

**Comment by monkpow** [comment]
Hey @paulmillr 
Thanks very much for this commit and the tests.   I'm not a fan of the current intercept interface, and am working to reconfigure this to make it a safer and more robust interface, and to allow this operation to be async when desired.      I'm reluctant for that reason to add more code here (preIntercept) at this moment.

I've added a test (52e44c7) that shows that I *think* you can modify response headers in the current intercept method.  Can you help me understand what cases you can't achieve today, and I'll either address those, or accept the preIntercept change if I can't address your concerns.

Thanks!

**Comment by paulmillr** [comment]
Really? That's like two lines of code. Not a big change. I've also spend more time and added the docs and tests.

The use case is the one mentioned in the readme. The webserver needs to clean-up HSTS stuff and make cookies unsecure. And i've definitely tried this with `intercept` more than once — the result response was always unchanged.

**Comment by monkpow** [comment]
Yeah, sorry.  I know its frustrating.   I find the intercept interface confusing, and a lot of bugs/requests are filed against it, so I assume others find it frustrating as well.    I'm working to break it down to something like:

modifyRequestBody
modifyRequestHeaders

Reading your code, docs, and description I believe intercept has created some confusion for you.

The code flow is like this:

1.   Receive proxy request
2.  Copy all proxy request headers to user request
3.  Intercept, passing the rsp (proxy response) and res (user response), and returning the body data.    Because rsp and res are passed by reference,  they can be modified in place (although the interface is not explicit about this).    At this point, you have to operate on the (user) res, because the (proxy) rsp is complete, and headers have already been copied to (user) res.     
4.  Intercept callback does some work to cleanup content-length headers in

**Comment by paulmillr** [comment]
I don't think the "pattern" is flexible enough. Not interested in spending more time.

**Comment by monkpow** [comment]
Cool, thanks for the conversation anyway -- that helped me understand the problem quite a bit more.

Curious if using the correct response object helped solve your use case.

**Pull request closed without merging**
