### PR TITLE
do gzip and gunzip asynchronously

### PR DESCRIPTION
**Pull request by raphaeleidus**
This PR makes the seamless unzipping and rezipping of `decorateUserRes` asynchronous.

### CODE REVIEW

**Comment by monkpow** [comment]
@raphaeleidus This code looks very good.   Could you explain a little more about why we want zipping/unzipping to be async?      It's probably obvious as soon as you point it out, but I'm not seeing it right away.

Thanks!

**Comment by monkpow** [comment]
@raphaeleidus yep, makes sense.    Let me review in detail, and I'll accept this.

**Comment by monkpow** [comment]
Hey @raphaeleidus,
Code looks pretty good.    Can you groom this branch so it just has the one gzip streaming commit on it?    I'll merge it right away.
Thanks,

**Comment by raphaeleidus** [comment]
squashed

**Comment by monkpow** [comment]
@raphaeleidus Thanks very much!

**Comment by monkpow** [comment]
@raphaeleidus Thanks for the recent activity.   I really appreciate it.   I'm going to wait a week to see what else we might get through, and then I'll publish a patch with these changes in it.

**Pull request merged**
