### PR TITLE
Swap out native http(s) for follow-redirects

### LINKED ISSUE #91: How to handle 301 redirects?
Hi @villadora,

I'm having some troubles when trying to proxy a host containing a 301 redirect.

Basically, I'm redirect(as usual) to target's domain, leaving my localhost proxy environment.

You can use as example: http://globo.com

Thank you in advance.

### PR DESCRIPTION
**Pull request by jonjaques**
This fixes #91.

Was getting an issue with an API that redirects all calls from their public endpoints. Tests passing.

### CODE REVIEW

**Comment by monkpow** [comment]
@jonjaques I like this change, but am, also working on swapping out the underlying request mechanism for one that also ```follow-redirects``` automatically.    I'm gonna put this on hold for the moment.

**Comment by jonjaques** [comment]
No worries. If/when you do add redirects, holler at me so I can update ma' deps. Good luck, I appreciate this package quite a bit!

**Comment by ceremonious** [comment]
Any updates on getting this merged in? Would be helpful for our project as well.

**Comment by topikuning** [comment]
> 
> 
> Any updates on getting this merged in? Would be helpful for our project as well.

I think it's better for merge by yourself for now, since there is no change event there are update 4 month ago

**Pull request closed without merging**
