### PR TITLE
Only set content-length header in non-GET requests.

### PR DESCRIPTION
**Pull request by fetimo**
Linked to issue https://github.com/villadora/express-http-proxy/issues/160

### CODE REVIEW

**Comment by monkpow** [comment]
@fetimo Thanks for the patch and the explanation in your issue.    Two items:

1. Can you help write a test case that demonstrates the issue?
2. I'm a bit nervous about assuming that GET always has no body.  Its allowed by the spec, although advised against.    I think a more conservative solution might be to have getContentLength return 0 for body of {}, or to clean {} off the body before submitting to getContentLength.   I'm hoping that #1 will help illuminate if this solves the problem for you as well.

Thanks!

**Comment by fetimo** [comment]
Hi @monkpow, I agree, you're way of cleaning {} off the body makes more sense. I spent some time on this the other day but it looks like you're in the middle of a substantial refactor. Is this something you're taking into consideration? Either way I'll close the PR for now as it doesn't seem to be relevant :)

**Comment by jdubray** [comment]
It would be good to add some warning on npm/github, AWS CloudFront does not like it at all, I spent a whole afternoon trying to figure out what was going on.
Even though it's technically allowed to have a body (though it is not mentioned here: https://tools.ietf.org/html/rfc2616#page-53), I have never seen in practice anyone doing it because you would lose the main benefits of get (URI, caching,...)
I have added: if (reqOpt.method === 'GET') { reqOpt.headers['content-length'] = 0; } prior to firing the proxyTargetRequest and it works fine.

**Comment by thejollyrogers** [comment]
I also ran into this problem and it does not play nicely with AWS CloudFront / API Gateway

**Pull request closed without merging**
