### PR TITLE
Forward path async

### PR DESCRIPTION
**Pull request by torhovland**

### CODE REVIEW

**Comment by monkpow** [comment]
Hi @torhovland 

Thanks very much for the patch and the tests.    I have a few questions about the structure of the change and it might help me to know the real world case you're solving for.    Can you give me one or two use cases I can use to think through the changes?   
Thanks again,

Nik

**Comment by torhovland** [comment]
Hi, Nik!

Sure, I implemented the change because I have the following need:

I have a web app that uses OpenID Connect for authentication, which means
it gets a JWK identity token. The app uses Service Worker for caching
application files, and it also uses PouchDB as a client-side database. This
means the app can run entirely offline (after the identity token exchange).
For permanent storage, as well as for syncing between clients, PouchDB will
sync with a CouchDB in the cloud. For this scenario it makes sense to use
the "one database per user" pattern in CouchDB. This means that each user
gets a specific URL to their backend database. For security, I am setting
up a proxy that provides a common endpoint for all users, but that will
demand the JWT token in an HTTP authorization header. It will then validate
the token, pull out the user's email address, and use that to generate a
proxy forwardPath to CouchDB.

Because some of the steps involve async actions, such as the token
validation using jsonwebtoken, I also need forwardPath to support async.

So that's why I implemented the change for my own use. Whether or not you
want to make use of this is of course entirely up to you, I won't mind if
you don't need it.

But if you think it makes sense, you might want to make the other options
promise-aware as well, e.g. filter, intercept, and so on.

Kind regards,
Tor

**Comment by monkpow** [comment]
Hey @torhovland, thanks.   The explanation and the use case make sense to me; thank you for the taking the time to make it so clear.  

I'm intrigued by making the code more promise-aware, and I like this change overall.

I feel the current patch impacts readability negatively.  The fault is more with the existing code than your patch; this area is tangled already.   I'd also like to experiment with how forwardPath and forwardPathAsync interact.

What I'd like to do is:
- grab the forwardSync tests, and apply them to master
- take a little bit longer look at how to where it makes sense to apply promises to proxy lifecycle
- apply the balance of this change.

I hope this is okay for you.   I really appreciate the patch and the conversation so far.

P.S. I also added some linting today, and that's causing your patch to fail.   The timing is bad luck, but I'll make a patch for your branch to get you up-to-date.

**Comment by monkpow** [comment]
https://github.com/villadora/express-http-proxy/tree/forwardPathAsync.rebased

@torhovland Just cleaned up the mess I made by adding linting.

**Comment by monkpow** [comment]
commit  a803c096ea51a2649469dbcff62b3619d3359a3e testing forwardPath is on master

**Comment by newmanw** [comment]
I am also looking at this patch to provide means to authenticate requests coming into the proxy.  I am using passportjs which is async.  Thanks @torhovland!

**Comment by monkpow** [comment]
Merged --  submitted on another CR after merging some recent changes to your line.    Thanks very much for the contribution..

**Pull request closed without merging**
