### PR TITLE
[ new ] - Adding decorateRequestAsync option for asynchronous decoration

### PR DESCRIPTION
**Pull request by ali-babaei**
Hi
Sorry, I was using your good module, but I see this feature missed...
Thanks to your good job man

### CODE REVIEW

**Comment by monkpow** [comment]
@ali-babaei Thanks for this change.   I'll review in detail later this week.

**Comment by LegNeato** [comment]
Any reason to have this as `decorateRequestAsync` instead of having `decorateRequest` handle both sync and async? It seems if you are adding the plumbing for async it would be trivial to just check if `decorateRequest` is thenable and if not make it into a Promise.

**Comment by monkpow** [comment]
@ali-babaei Thanks for the patch, I have been thinking about this for a while.   I do agree with @LegNeato about having a single property that handles both cases.      I'll review in detail over the next few days.

**Comment by LegNeato** [comment]
Turns out I needed this so I put up a PR rebased onto https://github.com/villadora/express-http-proxy/pull/155 with tests:

  https://github.com/villadora/express-http-proxy/pull/164

Hope you don't mind @ali-babaei!

@monkpow please take a look at https://github.com/villadora/express-http-proxy/pull/164 and see if I need any changes to land it.

**Comment by monkpow** [comment]
@ali-babaei Hi, thanks again for this patch.    This feature has been added on master, and I'll be releasing this version after some additional testing.

**Pull request closed without merging**
