### PR TITLE
fix to work with https, when passing a function instead of url.

### PR DESCRIPTION
**Pull request by gstroup**
added https option.

### CODE REVIEW

**Comment by gstroup** [comment]
Thanks!  Could you please publish the latest to npm??

I may be able to help with maintaining this project if no one else is able to.

**Comment by villadora** [comment]
thank you for helping that, sure. What's your github/npm id? I can add you
to the project

2016-06-03 1:23 GMT+08:00 Greg Stroup <notifications@github.com>:

**Comment by villadora** [comment]
I published a new version 0.7.0 to npm

2016-06-03 10:10 GMT+08:00 villa gogh <jky239@gmail.com>:

**Comment by gstroup** [comment]
Thanks for publishing.  My id is "gstroup" on github and npm.

**Comment by villadora** [comment]
Just added on both github and npm! It's very appreciated that you can help
with this project!

2016-06-04 0:58 GMT+08:00 Greg Stroup <notifications@github.com>:

**Comment by gstroup** [comment]
Thank you!  Glad I can help.

   -Greg

**Pull request merged**
