### PR TITLE
Make decorateRequest support functions that return a Promise.

### PR DESCRIPTION
**Pull request by LegNeato**
Requires https://github.com/villadora/express-http-proxy/pull/155. Will rebase on master once that lands so that only one commit shows up here.

### CODE REVIEW

**Comment by monkpow** [comment]
@LegNeato thanks for this change.   Overall, I like this.  One detail I'd like to discuss is 

```
 // If decorate returns request options, use those. Otherwise, use the
 // ones we already had.
```

Can you elaborate on this design decision?   I'm not sure of the case where I'd call decorate, but want to fall back silently if that returns nothing.    This violates my expectations, but maybe I'm not looking at it right.

**Comment by LegNeato** [comment]
Oh, I don't know...It just matches the code that was already there. Also, some existing tests don't return request options and they failed if I didn't do this.

**Comment by LegNeato** [comment]
Rebased on `master`.

**Comment by monkpow** [comment]
@LegNeato This feature is on master now, although its taken a journey since you posted this patch.    I'll be letting it bake in and aggressively testing over the next couple of weeks, and then plan to release this.

**Pull request closed without merging**
